// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PortOccupant 描述占用某个本地端口的进程。
 */
export class PortOccupant {
    /**
     * Creates a new PortOccupant instance.
     * @param {Partial<PortOccupant>} [$$source = {}] - The source object to create the PortOccupant.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * 进程名（取不到时为空）
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("killable" in $$source)) {
            /**
             * Killable 表示是否允许从界面上终止它。
             * 
             * 终止别人的进程是不可逆操作，宁可少给一个按钮也不能杀错：
             * 自身进程、以及取不到进程名（多半是权限不足看不到的系统进程）一律不给。
             * @member
             * @type {boolean}
             */
            this["killable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Reason 不可终止时的原因，直接展示给用户。
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (!("self" in $$source)) {
            /**
             * Self 该进程是否是本客户端自己（含内核子进程）。
             * @member
             * @type {boolean}
             */
            this["self"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortOccupant instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortOccupant}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortOccupant(/** @type {Partial<PortOccupant>} */($$parsedSource));
    }
}
