// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "./internal/utils/models.js";

/**
 * PortOccupantInfo 端口占用情况，供界面询问用户是否结束占用进程。
 */
export class PortOccupantInfo {
    /**
     * Creates a new PortOccupantInfo instance.
     * @param {Partial<PortOccupantInfo>} [$$source = {}] - The source object to create the PortOccupantInfo.
     */
    constructor($$source = {}) {
        if (!("port" in $$source)) {
            /**
             * 字符串以避免前端大整数精度问题，实际是端口号
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("occupants" in $$source)) {
            /**
             * 占用该端口的进程
             * @member
             * @type {utils$0.PortOccupant[]}
             */
            this["occupants"] = [];
        }
        if (!("killable" in $$source)) {
            /**
             * 是否有可终止的进程
             * @member
             * @type {boolean}
             */
            this["killable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortOccupantInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortOccupantInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("occupants" in $$parsedSource) {
            $$parsedSource["occupants"] = $$createField1_0($$parsedSource["occupants"]);
        }
        return new PortOccupantInfo(/** @type {Partial<PortOccupantInfo>} */($$parsedSource));
    }
}

/**
 * ProxyStatus 当前代理模式
 */
export class ProxyStatus {
    /**
     * Creates a new ProxyStatus instance.
     * @param {Partial<ProxyStatus>} [$$source = {}] - The source object to create the ProxyStatus.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * off / system / tun
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * TUN 转发目标名称
             * @member
             * @type {string}
             */
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyStatus(/** @type {Partial<ProxyStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = utils$0.PortOccupant.createFrom;
const $$createType1 = $Create.Array($$createType0);
