// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MyService 应用结构
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logger$0 from "./internal/logger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * AddChainProxy 添加链式代理
 * @param {models$0.ChainProxy} chain
 * @returns {$CancellablePromise<void>}
 */
export function AddChainProxy(chain) {
    return $Call.ByID(1770443933, chain);
}

/**
 * AddLoadBalancer 添加负载均衡节点
 * @param {models$0.LoadBalanceNode} lb
 * @returns {$CancellablePromise<void>}
 */
export function AddLoadBalancer(lb) {
    return $Call.ByID(4076290104, lb);
}

/**
 * AddRule 添加规则
 * @param {models$0.ProxyRule} rule
 * @returns {$CancellablePromise<void>}
 */
export function AddRule(rule) {
    return $Call.ByID(171616336, rule);
}

/**
 * AddSubscription 添加订阅
 * @param {string} name
 * @param {string} url
 * @param {boolean} autoUpdate
 * @param {number} updateInterval
 * @returns {$CancellablePromise<void>}
 */
export function AddSubscription(name, url, autoUpdate, updateInterval) {
    return $Call.ByID(3098545163, name, url, autoUpdate, updateInterval);
}

/**
 * CheckPortAvailable 检查端口是否可用
 * @param {number} port
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckPortAvailable(port) {
    return $Call.ByID(2195021613, port);
}

/**
 * ClearLogs 清空日志
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(808717079);
}

/**
 * CreateGroup 创建分组
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function CreateGroup(name, description) {
    return $Call.ByID(1307594394, name, description);
}

/**
 * DeleteChainProxy 删除链式代理
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteChainProxy(id) {
    return $Call.ByID(1334481423, id);
}

/**
 * DeleteGroup 删除分组
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(groupID) {
    return $Call.ByID(3822698067, groupID);
}

/**
 * DeleteLoadBalancer 删除负载均衡节点
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLoadBalancer(id) {
    return $Call.ByID(415466854, id);
}

/**
 * DeleteRule 删除规则
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRule(id) {
    return $Call.ByID(968490574, id);
}

/**
 * DeleteSubscription 删除订阅
 * @param {string} subID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSubscription(subID) {
    return $Call.ByID(1941456089, subID);
}

/**
 * DisableSystemProxy 取消系统代理
 * @returns {$CancellablePromise<void>}
 */
export function DisableSystemProxy() {
    return $Call.ByID(501106876);
}

/**
 * EnableSystemProxy 设置系统代理（支持普通节点、链式代理、负载均衡）
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function EnableSystemProxy(ruleID) {
    return $Call.ByID(3655017931, ruleID);
}

/**
 * ExportConfig 导出配置
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig() {
    return $Call.ByID(3058196731);
}

/**
 * FilterLogsByLevel 按级别过滤日志
 * @param {string} level
 * @returns {$CancellablePromise<logger$0.LogEntry[]>}
 */
export function FilterLogsByLevel(level) {
    return $Call.ByID(1218311751, level).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAutoStart 获取开机自启状态
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStart() {
    return $Call.ByID(3041441934);
}

/**
 * GetChainProxies 获取所有链式代理
 * @returns {$CancellablePromise<models$0.ChainProxy[]>}
 */
export function GetChainProxies() {
    return $Call.ByID(202626458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetGroups 获取所有分组
 * @returns {$CancellablePromise<models$0.Group[]>}
 */
export function GetGroups() {
    return $Call.ByID(3885822517).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetLoadBalancers 获取所有负载均衡节点
 * @returns {$CancellablePromise<models$0.LoadBalanceNode[]>}
 */
export function GetLoadBalancers() {
    return $Call.ByID(2240243908).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetLogs 获取所有日志
 * @returns {$CancellablePromise<logger$0.LogEntry[]>}
 */
export function GetLogs() {
    return $Call.ByID(3428980254).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetRules 获取所有规则
 * @returns {$CancellablePromise<models$0.ProxyRule[]>}
 */
export function GetRules() {
    return $Call.ByID(4270822776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetSubscriptions 获取所有订阅
 * @returns {$CancellablePromise<models$0.Subscription[]>}
 */
export function GetSubscriptions() {
    return $Call.ByID(3343587565).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetSystemProxyStatus 获取系统代理状态
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSystemProxyStatus() {
    return $Call.ByID(3546341710);
}

/**
 * ImportConfig 导入配置
 * @returns {$CancellablePromise<void>}
 */
export function ImportConfig() {
    return $Call.ByID(3036105508);
}

/**
 * ImportShareLinks 批量导入分享链接
 * @param {string} text
 * @returns {$CancellablePromise<number>}
 */
export function ImportShareLinks(text) {
    return $Call.ByID(4153373042, text);
}

/**
 * RecommendPort 推荐可用端口
 * @returns {$CancellablePromise<number>}
 */
export function RecommendPort() {
    return $Call.ByID(1630710424);
}

/**
 * SaveRuleOrder 保存规则排序
 * @param {string[]} orderedIDs
 * @returns {$CancellablePromise<void>}
 */
export function SaveRuleOrder(orderedIDs) {
    return $Call.ByID(2504508144, orderedIDs);
}

/**
 * SearchLogs 搜索日志
 * @param {string} keyword
 * @param {string} level
 * @returns {$CancellablePromise<logger$0.LogEntry[]>}
 */
export function SearchLogs(keyword, level) {
    return $Call.ByID(3057741528, keyword, level).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetAutoStart 设置开机自启
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enabled) {
    return $Call.ByID(2368911042, enabled);
}

/**
 * StartAllRulesInGroup 启动分组中的所有规则
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function StartAllRulesInGroup(groupID) {
    return $Call.ByID(121195111, groupID);
}

/**
 * StartChainProxy 启动链式代理
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartChainProxy(id) {
    return $Call.ByID(2192625838, id);
}

/**
 * StartLoadBalancer 启动负载均衡节点
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartLoadBalancer(id) {
    return $Call.ByID(3817337139, id);
}

/**
 * StartRule 启动规则
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartRule(id) {
    return $Call.ByID(2949408663, id);
}

/**
 * StopAllRulesInGroup 停止分组中的所有规则
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function StopAllRulesInGroup(groupID) {
    return $Call.ByID(1876496629, groupID);
}

/**
 * StopChainProxy 停止链式代理
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopChainProxy(id) {
    return $Call.ByID(3219092048, id);
}

/**
 * StopLoadBalancer 停止负载均衡节点
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopLoadBalancer(id) {
    return $Call.ByID(3297196641, id);
}

/**
 * StopRule 停止规则
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopRule(id) {
    return $Call.ByID(1057526277, id);
}

/**
 * TestAllRulesSpeed 测试所有规则的速度
 * @returns {$CancellablePromise<void>}
 */
export function TestAllRulesSpeed() {
    return $Call.ByID(3758912688);
}

/**
 * TestRuleSpeed 测试单个规则的速度
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function TestRuleSpeed(ruleID) {
    return $Call.ByID(1601355076, ruleID);
}

/**
 * TestSelectedRulesSpeed 测试选中的规则速度
 * @param {string[]} ruleIDs
 * @returns {$CancellablePromise<void>}
 */
export function TestSelectedRulesSpeed(ruleIDs) {
    return $Call.ByID(2689257396, ruleIDs);
}

/**
 * UpdateChainProxy 更新链式代理
 * @param {models$0.ChainProxy} chain
 * @returns {$CancellablePromise<void>}
 */
export function UpdateChainProxy(chain) {
    return $Call.ByID(2627418393, chain);
}

/**
 * UpdateLoadBalancer 更新负载均衡节点
 * @param {models$0.LoadBalanceNode} lb
 * @returns {$CancellablePromise<void>}
 */
export function UpdateLoadBalancer(lb) {
    return $Call.ByID(682714724, lb);
}

/**
 * UpdateRule 更新规则
 * @param {string} id
 * @param {models$0.ProxyRule} updatedRule
 * @returns {$CancellablePromise<void>}
 */
export function UpdateRule(id, updatedRule) {
    return $Call.ByID(128722644, id, updatedRule);
}

/**
 * UpdateSubscriptionByID 更新指定订阅
 * @param {string} subID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSubscriptionByID(subID) {
    return $Call.ByID(4157224703, subID);
}

// Private type creation functions
const $$createType0 = logger$0.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.ChainProxy.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Group.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.LoadBalanceNode.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.ProxyRule.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.Subscription.createFrom;
const $$createType11 = $Create.Array($$createType10);
