// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MyService 应用结构
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logger$0 from "./internal/logger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * AddChainProxy 添加链式代理
 * @param {models$0.ChainProxy} chain
 * @returns {$CancellablePromise<void>}
 */
export function AddChainProxy(chain) {
    return $Call.ByID(1770443933, chain);
}

/**
 * AddLoadBalancer 添加负载均衡节点
 * @param {models$0.LoadBalanceNode} lb
 * @returns {$CancellablePromise<void>}
 */
export function AddLoadBalancer(lb) {
    return $Call.ByID(4076290104, lb);
}

/**
 * AddRule 添加规则
 * @param {models$0.ProxyRule} rule
 * @returns {$CancellablePromise<void>}
 */
export function AddRule(rule) {
    return $Call.ByID(171616336, rule);
}

/**
 * AddSubscription 添加订阅
 * updateMode: 更新方式 direct/system/proxy；updateProxyID: 更新方式为 proxy 时使用的节点 ID
 * @param {string} name
 * @param {string} url
 * @param {boolean} autoUpdate
 * @param {number} updateInterval
 * @param {string} updateMode
 * @param {string} updateProxyID
 * @returns {$CancellablePromise<void>}
 */
export function AddSubscription(name, url, autoUpdate, updateInterval, updateMode, updateProxyID) {
    return $Call.ByID(3098545163, name, url, autoUpdate, updateInterval, updateMode, updateProxyID);
}

/**
 * CheckAllNodesHealth 检测全部节点健康状态
 * @returns {$CancellablePromise<void>}
 */
export function CheckAllNodesHealth() {
    return $Call.ByID(2473554395);
}

/**
 * CheckNodeHealth 检测单个节点健康状态
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function CheckNodeHealth(ruleID) {
    return $Call.ByID(2461525239, ruleID);
}

/**
 * CheckPortAvailable 检查端口是否可用
 * @param {number} port
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckPortAvailable(port) {
    return $Call.ByID(2195021613, port);
}

/**
 * CheckSelectedNodesHealth 检测选中节点健康状态
 * @param {string[]} ruleIDs
 * @returns {$CancellablePromise<void>}
 */
export function CheckSelectedNodesHealth(ruleIDs) {
    return $Call.ByID(543227979, ruleIDs);
}

/**
 * ClearLogs 清空日志
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(808717079);
}

/**
 * CreateGroup 创建分组
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function CreateGroup(name, description) {
    return $Call.ByID(1307594394, name, description);
}

/**
 * DeleteChainProxy 删除链式代理
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteChainProxy(id) {
    return $Call.ByID(1334481423, id);
}

/**
 * DeleteGroup 删除分组
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(groupID) {
    return $Call.ByID(3822698067, groupID);
}

/**
 * DeleteLoadBalancer 删除负载均衡节点
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLoadBalancer(id) {
    return $Call.ByID(415466854, id);
}

/**
 * DeleteRule 删除规则
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRule(id) {
    return $Call.ByID(968490574, id);
}

/**
 * DeleteSubscription 删除订阅
 * @param {string} subID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSubscription(subID) {
    return $Call.ByID(1941456089, subID);
}

/**
 * DisableSystemProxy 取消系统代理
 * @returns {$CancellablePromise<void>}
 */
export function DisableSystemProxy() {
    return $Call.ByID(501106876);
}

/**
 * EditSubscription 编辑订阅（名称/URL/自动更新/更新间隔/更新方式）。
 * 不触发订阅内容更新，只修改元数据；改名会同步分组名和该订阅下节点的分组名，
 * 改 URL 会同步节点的订阅链接，最后按新配置重设自动更新定时任务。
 * @param {string} subID
 * @param {string} name
 * @param {string} url
 * @param {boolean} autoUpdate
 * @param {number} updateInterval
 * @param {string} updateMode
 * @param {string} updateProxyID
 * @returns {$CancellablePromise<void>}
 */
export function EditSubscription(subID, name, url, autoUpdate, updateInterval, updateMode, updateProxyID) {
    return $Call.ByID(1363501906, subID, name, url, autoUpdate, updateInterval, updateMode, updateProxyID);
}

/**
 * EnableSystemProxy 设置系统代理（支持普通节点、链式代理、负载均衡）
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function EnableSystemProxy(ruleID) {
    return $Call.ByID(3655017931, ruleID);
}

/**
 * ExportConfig 导出配置（标准格式，包含版本信息）
 * ruleIds 为空时导出全部规则，非空时仅导出选中的规则及其关联项：
 *   - 仅当链式代理/负载均衡的全部成员节点都被选中时才导出该链式代理/负载均衡
 *   - 仅导出被导出内容引用到的分组
 *   - includeSubscriptions 控制是否导出订阅及订阅分组；不导出时订阅节点转为手动节点
 * @param {string[]} ruleIds
 * @param {boolean} includeSubscriptions
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig(ruleIds, includeSubscriptions) {
    return $Call.ByID(3058196731, ruleIds, includeSubscriptions);
}

/**
 * FilterLogsByLevel 按级别过滤日志
 * @param {string} level
 * @returns {$CancellablePromise<logger$0.LogEntry[]>}
 */
export function FilterLogsByLevel(level) {
    return $Call.ByID(1218311751, level).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAutoStart 获取开机自启状态（从系统配置读取）
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStart() {
    return $Call.ByID(3041441934);
}

/**
 * GetChainProxies 获取所有链式代理
 * @returns {$CancellablePromise<models$0.ChainProxy[]>}
 */
export function GetChainProxies() {
    return $Call.ByID(202626458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetGroups 获取所有分组
 * @returns {$CancellablePromise<models$0.Group[]>}
 */
export function GetGroups() {
    return $Call.ByID(3885822517).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetHealthCheckConfig 获取健康检查配置
 * @returns {$CancellablePromise<models$0.HealthCheckConfig>}
 */
export function GetHealthCheckConfig() {
    return $Call.ByID(1768486251).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetLoadBalancers 获取所有负载均衡节点
 * @returns {$CancellablePromise<models$0.LoadBalanceNode[]>}
 */
export function GetLoadBalancers() {
    return $Call.ByID(2240243908).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetLogs 获取所有日志
 * @returns {$CancellablePromise<logger$0.LogEntry[]>}
 */
export function GetLogs() {
    return $Call.ByID(3428980254).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetRules 获取所有规则
 * @returns {$CancellablePromise<models$0.ProxyRule[]>}
 */
export function GetRules() {
    return $Call.ByID(4270822776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetSubscriptions 获取所有订阅
 * @returns {$CancellablePromise<models$0.Subscription[]>}
 */
export function GetSubscriptions() {
    return $Call.ByID(3343587565).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetSystemProxyStatus 获取系统代理状态
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSystemProxyStatus() {
    return $Call.ByID(3546341710);
}

/**
 * ImportConfig 导入配置（支持标准导出格式和旧格式，含重复检测和校验）
 * @returns {$CancellablePromise<models$0.ImportResult | null>}
 */
export function ImportConfig() {
    return $Call.ByID(3036105508).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ImportShareLinks 批量导入分享链接（返回详细结果）
 * @param {string} text
 * @returns {$CancellablePromise<models$0.ImportShareResult | null>}
 */
export function ImportShareLinks(text) {
    return $Call.ByID(4153373042, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * RecommendPort 推荐可用端口
 * @returns {$CancellablePromise<number>}
 */
export function RecommendPort() {
    return $Call.ByID(1630710424);
}

/**
 * ResetRuleTraffic 清零节点流量统计（ruleID 为空时清零全部节点）
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function ResetRuleTraffic(ruleID) {
    return $Call.ByID(485055981, ruleID);
}

/**
 * SaveRuleOrder 保存规则排序
 * @param {string[]} orderedIDs
 * @returns {$CancellablePromise<void>}
 */
export function SaveRuleOrder(orderedIDs) {
    return $Call.ByID(2504508144, orderedIDs);
}

/**
 * SearchLogs 搜索日志
 * @param {string} keyword
 * @param {string} level
 * @returns {$CancellablePromise<logger$0.LogEntry[]>}
 */
export function SearchLogs(keyword, level) {
    return $Call.ByID(3057741528, keyword, level).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetAutoStart 设置开机自启
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enabled) {
    return $Call.ByID(2368911042, enabled);
}

/**
 * SetHealthCheckConfig 更新健康检查配置
 * @param {models$0.HealthCheckConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetHealthCheckConfig(cfg) {
    return $Call.ByID(3960229671, cfg);
}

/**
 * SetSubscriptionUpdateMode 设置订阅的更新方式
 * mode: direct（直连）/ system（系统代理）/ proxy（指定节点，proxyID 为节点/链式代理/负载均衡的 ID）
 * @param {string} subID
 * @param {string} mode
 * @param {string} proxyID
 * @returns {$CancellablePromise<void>}
 */
export function SetSubscriptionUpdateMode(subID, mode, proxyID) {
    return $Call.ByID(2451826590, subID, mode, proxyID);
}

/**
 * StartAllRulesInGroup 启动分组中的所有规则
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function StartAllRulesInGroup(groupID) {
    return $Call.ByID(121195111, groupID);
}

/**
 * StartChainProxy 启动链式代理
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartChainProxy(id) {
    return $Call.ByID(2192625838, id);
}

/**
 * StartLoadBalancer 启动负载均衡节点
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartLoadBalancer(id) {
    return $Call.ByID(3817337139, id);
}

/**
 * StartNodes 批量启动节点（普通节点/负载均衡/链式代理），并发执行、只保存一次配置。
 * 相比前端逐个调用 StartRule，避免了 N 次串行的进程启动 + N 次写盘导致的卡顿。
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function StartNodes(ids) {
    return $Call.ByID(2356274542, ids);
}

/**
 * StartRule 启动规则
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartRule(id) {
    return $Call.ByID(2949408663, id);
}

/**
 * StopAllRulesInGroup 停止分组中的所有规则
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function StopAllRulesInGroup(groupID) {
    return $Call.ByID(1876496629, groupID);
}

/**
 * StopChainProxy 停止链式代理
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopChainProxy(id) {
    return $Call.ByID(3219092048, id);
}

/**
 * StopLoadBalancer 停止负载均衡节点
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopLoadBalancer(id) {
    return $Call.ByID(3297196641, id);
}

/**
 * StopNodes 批量停止节点，并发执行、只保存一次配置。
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function StopNodes(ids) {
    return $Call.ByID(904660584, ids);
}

/**
 * StopRule 停止规则
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopRule(id) {
    return $Call.ByID(1057526277, id);
}

/**
 * TestAllRulesSpeed 测试所有规则的速度
 * @returns {$CancellablePromise<void>}
 */
export function TestAllRulesSpeed() {
    return $Call.ByID(3758912688);
}

/**
 * TestRuleSpeed 测试单个规则的速度
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function TestRuleSpeed(ruleID) {
    return $Call.ByID(1601355076, ruleID);
}

/**
 * TestSelectedRulesSpeed 测试选中的规则速度
 * @param {string[]} ruleIDs
 * @returns {$CancellablePromise<void>}
 */
export function TestSelectedRulesSpeed(ruleIDs) {
    return $Call.ByID(2689257396, ruleIDs);
}

/**
 * UpdateChainProxy 更新链式代理
 * @param {models$0.ChainProxy} chain
 * @returns {$CancellablePromise<void>}
 */
export function UpdateChainProxy(chain) {
    return $Call.ByID(2627418393, chain);
}

/**
 * UpdateLoadBalancer 更新负载均衡节点
 * @param {models$0.LoadBalanceNode} lb
 * @returns {$CancellablePromise<void>}
 */
export function UpdateLoadBalancer(lb) {
    return $Call.ByID(682714724, lb);
}

/**
 * UpdateRule 更新规则
 * @param {string} id
 * @param {models$0.ProxyRule} updatedRule
 * @returns {$CancellablePromise<void>}
 */
export function UpdateRule(id, updatedRule) {
    return $Call.ByID(128722644, id, updatedRule);
}

/**
 * UpdateSubscriptionByID 更新指定订阅
 * @param {string} subID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSubscriptionByID(subID) {
    return $Call.ByID(4157224703, subID);
}

// Private type creation functions
const $$createType0 = logger$0.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.ChainProxy.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Group.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.HealthCheckConfig.createFrom;
const $$createType7 = models$0.LoadBalanceNode.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.ProxyRule.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = models$0.Subscription.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = models$0.ImportResult.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = models$0.ImportShareResult.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
