// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    GRPCSettings,
    H2Settings,
    ProxyRule,
    ProxySettings,
    TLSSettings,
    WSSettings
} from "./models.js";
