// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChainProxy 链式代理配置
 */
export class ChainProxy {
    /**
     * Creates a new ChainProxy instance.
     * @param {Partial<ChainProxy>} [$$source = {}] - The source object to create the ChainProxy.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * 别名
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("localType" in $$source)) {
            /**
             * 本地代理类型
             * @member
             * @type {string}
             */
            this["localType"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * 本地代理端口
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("chainNodes" in $$source)) {
            /**
             * 链中的节点ID列表（可以包含普通节点或LB节点ID）
             * @member
             * @type {string[]}
             */
            this["chainNodes"] = [];
        }
        if (!("enabled" in $$source)) {
            /**
             * 启动状态
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("processId" in $$source)) {
            /**
             * 进程ID
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("realIp" in $$source)) {
            /**
             * 真实IP
             * @member
             * @type {string}
             */
            this["realIp"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * 最近一次启动失败/不通的原因（成功后清空）
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 所属分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("groupName" in $$source)) {
            /**
             * 所属分组名称
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (!("latency" in $$source)) {
            /**
             * 测速相关字段（通过本地代理端口测试）
             * 延迟（毫秒）
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            /**
             * 下载速度（MB/s）
             * @member
             * @type {number}
             */
            this["downloadSpeed"] = 0;
        }
        if (!("lastTestTime" in $$source)) {
            /**
             * 最后测速时间
             * @member
             * @type {string}
             */
            this["lastTestTime"] = "";
        }
        if (!("testStatus" in $$source)) {
            /**
             * 测速状态: idle, testing, success, failed
             * @member
             * @type {string}
             */
            this["testStatus"] = "";
        }
        if (!("healthStatus" in $$source)) {
            /**
             * 健康检查相关字段（通过本地代理端口检测，需已启动）
             * online, high_latency, timeout, checking
             * @member
             * @type {string}
             */
            this["healthStatus"] = "";
        }
        if (!("healthLatency" in $$source)) {
            /**
             * 健康检查延迟（毫秒）
             * @member
             * @type {number}
             */
            this["healthLatency"] = 0;
        }
        if (!("lastHealthCheck" in $$source)) {
            /**
             * 最后健康检查时间
             * @member
             * @type {string}
             */
            this["lastHealthCheck"] = "";
        }
        if (!("traffic" in $$source)) {
            /**
             * 流量统计相关字段
             * 累计流量统计
             * @member
             * @type {TrafficStats}
             */
            this["traffic"] = (new TrafficStats());
        }
        if (!("lastStartTime" in $$source)) {
            /**
             * 最近启动时间
             * @member
             * @type {string}
             */
            this["lastStartTime"] = "";
        }
        if (!("lastStopTime" in $$source)) {
            /**
             * 最近停止时间
             * @member
             * @type {string}
             */
            this["lastStopTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChainProxy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChainProxy}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField18_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chainNodes" in $$parsedSource) {
            $$parsedSource["chainNodes"] = $$createField4_0($$parsedSource["chainNodes"]);
        }
        if ("traffic" in $$parsedSource) {
            $$parsedSource["traffic"] = $$createField18_0($$parsedSource["traffic"]);
        }
        return new ChainProxy(/** @type {Partial<ChainProxy>} */($$parsedSource));
    }
}

/**
 * GRPCSettings gRPC配置
 */
export class GRPCSettings {
    /**
     * Creates a new GRPCSettings instance.
     * @param {Partial<GRPCSettings>} [$$source = {}] - The source object to create the GRPCSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * gRPC服务名
             * @member
             * @type {string | undefined}
             */
            this["serviceName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GRPCSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GRPCSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GRPCSettings(/** @type {Partial<GRPCSettings>} */($$parsedSource));
    }
}

/**
 * Group 节点分组。
 * 
 * 一个分组可以关联多个订阅（多个订阅的节点汇入同一分组），因此这里不再保存
 * 单个 SubscriptionID —— 归属关系以 Subscription.GroupID 为准，反向查询遍历订阅列表即可。
 */
export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 分组ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 分组名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 分组描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 来源: manual, subscription
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

/**
 * H2Settings HTTP/2配置
 */
export class H2Settings {
    /**
     * Creates a new H2Settings instance.
     * @param {Partial<H2Settings>} [$$source = {}] - The source object to create the H2Settings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * HTTP/2路径
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP/2 Host
             * @member
             * @type {string[] | undefined}
             */
            this["host"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new H2Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {H2Settings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("host" in $$parsedSource) {
            $$parsedSource["host"] = $$createField1_0($$parsedSource["host"]);
        }
        return new H2Settings(/** @type {Partial<H2Settings>} */($$parsedSource));
    }
}

/**
 * HTTPAPIConfig HTTP API 服务配置。
 */
export class HTTPAPIConfig {
    /**
     * Creates a new HTTPAPIConfig instance.
     * @param {Partial<HTTPAPIConfig>} [$$source = {}] - The source object to create the HTTPAPIConfig.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("authEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["authEnabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPAPIConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HTTPAPIConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPAPIConfig(/** @type {Partial<HTTPAPIConfig>} */($$parsedSource));
    }
}

/**
 * HealthCheckConfig 健康检查全局配置
 */
export class HealthCheckConfig {
    /**
     * Creates a new HealthCheckConfig instance.
     * @param {Partial<HealthCheckConfig>} [$$source = {}] - The source object to create the HealthCheckConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * 是否启用后台自动检测
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("intervalSec" in $$source)) {
            /**
             * 检测周期（秒）
             * @member
             * @type {number}
             */
            this["intervalSec"] = 0;
        }
        if (!("timeoutSec" in $$source)) {
            /**
             * 单节点检测超时（秒）
             * @member
             * @type {number}
             */
            this["timeoutSec"] = 0;
        }
        if (!("latencyThreshold" in $$source)) {
            /**
             * 延迟较高阈值（毫秒）
             * @member
             * @type {number}
             */
            this["latencyThreshold"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthCheckConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthCheckConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthCheckConfig(/** @type {Partial<HealthCheckConfig>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入结果
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("rulesImported" in $$source)) {
            /**
             * 导入的规则数
             * @member
             * @type {number}
             */
            this["rulesImported"] = 0;
        }
        if (!("rulesSkipped" in $$source)) {
            /**
             * 跳过的重复规则数
             * @member
             * @type {number}
             */
            this["rulesSkipped"] = 0;
        }
        if (!("groupsImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groupsImported"] = 0;
        }
        if (!("subsImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["subsImported"] = 0;
        }
        if (!("chainImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chainImported"] = 0;
        }
        if (!("lbImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lbImported"] = 0;
        }
        if (!("relayImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["relayImported"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * 错误信息列表
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * 警告信息列表
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField8_0($$parsedSource["errors"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField9_0($$parsedSource["warnings"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * ImportShareResult 批量导入分享链接结果
 */
export class ImportShareResult {
    /**
     * Creates a new ImportShareResult instance.
     * @param {Partial<ImportShareResult>} [$$source = {}] - The source object to create the ImportShareResult.
     */
    constructor($$source = {}) {
        if (!("successCount" in $$source)) {
            /**
             * 成功数
             * @member
             * @type {number}
             */
            this["successCount"] = 0;
        }
        if (!("failCount" in $$source)) {
            /**
             * 失败数
             * @member
             * @type {number}
             */
            this["failCount"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * 每条失败的详细信息
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportShareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportShareResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new ImportShareResult(/** @type {Partial<ImportShareResult>} */($$parsedSource));
    }
}

/**
 * LoadBalanceNode 故障转移节点
 */
export class LoadBalanceNode {
    /**
     * Creates a new LoadBalanceNode instance.
     * @param {Partial<LoadBalanceNode>} [$$source = {}] - The source object to create the LoadBalanceNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * 别名
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("localType" in $$source)) {
            /**
             * 本地代理类型: mixed（同时支持 HTTP/SOCKS5）
             * @member
             * @type {string}
             */
            this["localType"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * 本地代理端口
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("nodeIds" in $$source)) {
            /**
             * 子节点 ID 列表
             * @member
             * @type {string[]}
             */
            this["nodeIds"] = [];
        }
        if (!("enabled" in $$source)) {
            /**
             * 启动状态
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("processId" in $$source)) {
            /**
             * 进程ID
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("realIp" in $$source)) {
            /**
             * 真实IP
             * @member
             * @type {string}
             */
            this["realIp"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * 最近一次启动失败/不通的原因（成功后清空）
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 所属分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("groupName" in $$source)) {
            /**
             * 所属分组名称
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (!("latency" in $$source)) {
            /**
             * 测速相关字段（通过本地代理端口测试）
             * 延迟（毫秒）
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            /**
             * 下载速度（MB/s）
             * @member
             * @type {number}
             */
            this["downloadSpeed"] = 0;
        }
        if (!("lastTestTime" in $$source)) {
            /**
             * 最后测速时间
             * @member
             * @type {string}
             */
            this["lastTestTime"] = "";
        }
        if (!("testStatus" in $$source)) {
            /**
             * 测速状态: idle, testing, success, failed
             * @member
             * @type {string}
             */
            this["testStatus"] = "";
        }
        if (!("healthStatus" in $$source)) {
            /**
             * 健康检查相关字段（通过本地代理端口检测，需已启动）
             * online, high_latency, timeout, checking
             * @member
             * @type {string}
             */
            this["healthStatus"] = "";
        }
        if (!("healthLatency" in $$source)) {
            /**
             * 健康检查延迟（毫秒）
             * @member
             * @type {number}
             */
            this["healthLatency"] = 0;
        }
        if (!("lastHealthCheck" in $$source)) {
            /**
             * 最后健康检查时间
             * @member
             * @type {string}
             */
            this["lastHealthCheck"] = "";
        }
        if (!("traffic" in $$source)) {
            /**
             * 流量统计相关字段
             * 累计流量统计
             * @member
             * @type {TrafficStats}
             */
            this["traffic"] = (new TrafficStats());
        }
        if (!("lastStartTime" in $$source)) {
            /**
             * 最近启动时间
             * @member
             * @type {string}
             */
            this["lastStartTime"] = "";
        }
        if (!("lastStopTime" in $$source)) {
            /**
             * 最近停止时间
             * @member
             * @type {string}
             */
            this["lastStopTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadBalanceNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadBalanceNode}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField18_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodeIds" in $$parsedSource) {
            $$parsedSource["nodeIds"] = $$createField4_0($$parsedSource["nodeIds"]);
        }
        if ("traffic" in $$parsedSource) {
            $$parsedSource["traffic"] = $$createField18_0($$parsedSource["traffic"]);
        }
        return new LoadBalanceNode(/** @type {Partial<LoadBalanceNode>} */($$parsedSource));
    }
}

/**
 * PortConflict 描述启动时发现的跨客户端本地端口冲突。
 */
export class PortConflict {
    /**
     * Creates a new PortConflict instance.
     * @param {Partial<PortConflict>} [$$source = {}] - The source object to create the PortConflict.
     */
    constructor($$source = {}) {
        if (!("resourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resourceId"] = "";
        }
        if (!("resourceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resourceType"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("ownerExecutablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownerExecutablePath"] = "";
        }
        if (!("ownerConfigPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownerConfigPath"] = "";
        }
        if (!("ownerResourceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownerResourceType"] = "";
        }
        if (!("ownerAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownerAlias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortConflict(/** @type {Partial<PortConflict>} */($$parsedSource));
    }
}

/**
 * PreProxyConfig 全局前置代理配置（用于 API 回显）
 */
export class PreProxyConfig {
    /**
     * Creates a new PreProxyConfig instance.
     * @param {Partial<PreProxyConfig>} [$$source = {}] - The source object to create the PreProxyConfig.
     */
    constructor($$source = {}) {
        if (!("nodeId" in $$source)) {
            /**
             * 前置节点 ID，空表示未启用
             * @member
             * @type {string}
             */
            this["nodeId"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * 节点别名（只读回显）
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreProxyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreProxyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreProxyConfig(/** @type {Partial<PreProxyConfig>} */($$parsedSource));
    }
}

/**
 * ProxyRule 代理规则结构
 */
export class ProxyRule {
    /**
     * Creates a new ProxyRule instance.
     * @param {Partial<ProxyRule>} [$$source = {}] - The source object to create the ProxyRule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * 别名
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("localType" in $$source)) {
            /**
             * 本地代理类型: mixed（同时支持 HTTP/SOCKS5），旧值 socks/http 兼容处理
             * @member
             * @type {string}
             */
            this["localType"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * 本地代理端口
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("protocol" in $$source)) {
            /**
             * 远程协议类型: shadowsocks, vmess, vless, trojan, hysteria2, tuic
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("serverAddr" in $$source)) {
            /**
             * 服务器地址
             * @member
             * @type {string}
             */
            this["serverAddr"] = "";
        }
        if (!("serverPort" in $$source)) {
            /**
             * 服务器端口
             * @member
             * @type {number}
             */
            this["serverPort"] = 0;
        }
        if (!("settings" in $$source)) {
            /**
             * 协议相关配置
             * @member
             * @type {ProxySettings}
             */
            this["settings"] = (new ProxySettings());
        }
        if (!("realIp" in $$source)) {
            /**
             * 真实IP
             * @member
             * @type {string}
             */
            this["realIp"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * 启动状态
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("processId" in $$source)) {
            /**
             * 进程ID
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * 最近一次启动失败/不通的原因（成功后清空）
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("latency" in $$source)) {
            /**
             * 测速相关字段
             * TCP 延迟（毫秒）
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            /**
             * 下载速度（MB/s）
             * @member
             * @type {number}
             */
            this["downloadSpeed"] = 0;
        }
        if (!("lastTestTime" in $$source)) {
            /**
             * 最后测速时间
             * @member
             * @type {string}
             */
            this["lastTestTime"] = "";
        }
        if (!("testStatus" in $$source)) {
            /**
             * 测速状态: idle, testing, success, failed
             * @member
             * @type {string}
             */
            this["testStatus"] = "";
        }
        if (!("healthStatus" in $$source)) {
            /**
             * 健康检查相关字段
             * 健康状态: 空, checking, online, high_latency, timeout, dns_failed, tls_failed, reality_failed, ipv6_only
             * @member
             * @type {string}
             */
            this["healthStatus"] = "";
        }
        if (!("healthLatency" in $$source)) {
            /**
             * 健康检查延迟（毫秒）
             * @member
             * @type {number}
             */
            this["healthLatency"] = 0;
        }
        if (!("lastHealthCheck" in $$source)) {
            /**
             * 最后健康检查时间
             * @member
             * @type {string}
             */
            this["lastHealthCheck"] = "";
        }
        if (!("traffic" in $$source)) {
            /**
             * 流量统计相关字段
             * 累计流量统计
             * @member
             * @type {TrafficStats}
             */
            this["traffic"] = (new TrafficStats());
        }
        if (!("lastStartTime" in $$source)) {
            /**
             * 最近启动时间
             * @member
             * @type {string}
             */
            this["lastStartTime"] = "";
        }
        if (!("lastStopTime" in $$source)) {
            /**
             * 最近停止时间
             * @member
             * @type {string}
             */
            this["lastStopTime"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 分组相关字段
             * 所属分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("groupName" in $$source)) {
            /**
             * 所属分组名称
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 来源订阅ID（一个分组可含多个订阅的节点）
             * @member
             * @type {string | undefined}
             */
            this["subscriptionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 订阅链接（如果来自订阅）
             * @member
             * @type {string | undefined}
             */
            this["subscriptionUrl"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * 来源: manual（手动添加）, subscription（订阅导入）
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyRule}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField19_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField7_0($$parsedSource["settings"]);
        }
        if ("traffic" in $$parsedSource) {
            $$parsedSource["traffic"] = $$createField19_0($$parsedSource["traffic"]);
        }
        return new ProxyRule(/** @type {Partial<ProxyRule>} */($$parsedSource));
    }
}

/**
 * ProxySettings 代理协议设置（根据协议类型使用不同字段）
 */
export class ProxySettings {
    /**
     * Creates a new ProxySettings instance.
     * @param {Partial<ProxySettings>} [$$source = {}] - The source object to create the ProxySettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Shadowsocks 配置
             * 加密方法
             * @member
             * @type {string | undefined}
             */
            this["ssMethod"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 密码
             * @member
             * @type {string | undefined}
             */
            this["ssPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VMess 配置
             * 用户ID (UUID)
             * @member
             * @type {string | undefined}
             */
            this["vmessUserId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 额外ID
             * @member
             * @type {number | undefined}
             */
            this["vmessAlterId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密方式 (auto, aes-128-gcm, chacha20-poly1305, none)
             * @member
             * @type {string | undefined}
             */
            this["vmessSecurity"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VLESS 配置
             * 用户ID (UUID)
             * @member
             * @type {string | undefined}
             */
            this["vlessUserId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 流控模式 (xtls-rprx-vision等)
             * @member
             * @type {string | undefined}
             */
            this["vlessFlow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密方式（通常为 none）
             * @member
             * @type {string | undefined}
             */
            this["vlessEncryption"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Trojan 配置
             * Trojan密码
             * @member
             * @type {string | undefined}
             */
            this["trojanPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP 代理配置
             * HTTP 代理用户名（可选）
             * @member
             * @type {string | undefined}
             */
            this["httpUsername"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP 代理密码（可选）
             * @member
             * @type {string | undefined}
             */
            this["httpPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SOCKS 代理配置
             * SOCKS 代理用户名（可选）
             * @member
             * @type {string | undefined}
             */
            this["socksUsername"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SOCKS 代理密码（可选）
             * @member
             * @type {string | undefined}
             */
            this["socksPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SOCKS 版本 (socks4, socks5, 默认 socks5)
             * @member
             * @type {string | undefined}
             */
            this["socksVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Hysteria2 配置
             * 认证密码
             * @member
             * @type {string | undefined}
             */
            this["hy2Password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 混淆类型（salamander）
             * @member
             * @type {string | undefined}
             */
            this["hy2Obfs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 混淆密码
             * @member
             * @type {string | undefined}
             */
            this["hy2ObfsPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 上行带宽限制 (Mbps)，0 表示自动（BBR）
             * @member
             * @type {number | undefined}
             */
            this["hy2UpMbps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 下行带宽限制 (Mbps)，0 表示自动（BBR）
             * @member
             * @type {number | undefined}
             */
            this["hy2DownMbps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 证书指纹固定（自签证书）；sing-box 无法用证书指纹校验，故有此值时启用 insecure
             * @member
             * @type {string | undefined}
             */
            this["hy2PinSHA256"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 端口跳跃范围，如 "35000-39000"（对应 mport）
             * @member
             * @type {string | undefined}
             */
            this["hy2Ports"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TUIC v5 配置
             * 用户 UUID
             * @member
             * @type {string | undefined}
             */
            this["tuicUserId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 密码
             * @member
             * @type {string | undefined}
             */
            this["tuicPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 拥塞控制: bbr, cubic, new_reno
             * @member
             * @type {string | undefined}
             */
            this["tuicCongestion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * UDP 中继模式: native, quic
             * @member
             * @type {string | undefined}
             */
            this["tuicUdpRelayMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 通用传输层配置
             * 传输协议: tcp, ws, grpc, h2
             * @member
             * @type {string | undefined}
             */
            this["network"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 传输层安全: none, tls, reality
             * @member
             * @type {string | undefined}
             */
            this["security"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TLS配置
             * @member
             * @type {TLSSettings | null | undefined}
             */
            this["tls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * REALITY 配置（security=reality 时必填）
             * @member
             * @type {RealitySettings | null | undefined}
             */
            this["reality"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * WebSocket配置
             * @member
             * @type {WSSettings | null | undefined}
             */
            this["ws"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * gRPC配置
             * @member
             * @type {GRPCSettings | null | undefined}
             */
            this["grpc"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP/2配置
             * @member
             * @type {H2Settings | null | undefined}
             */
            this["h2"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxySettings}
     */
    static createFrom($$source = {}) {
        const $$createField27_0 = $$createType4;
        const $$createField28_0 = $$createType6;
        const $$createField29_0 = $$createType8;
        const $$createField30_0 = $$createType10;
        const $$createField31_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tls" in $$parsedSource) {
            $$parsedSource["tls"] = $$createField27_0($$parsedSource["tls"]);
        }
        if ("reality" in $$parsedSource) {
            $$parsedSource["reality"] = $$createField28_0($$parsedSource["reality"]);
        }
        if ("ws" in $$parsedSource) {
            $$parsedSource["ws"] = $$createField29_0($$parsedSource["ws"]);
        }
        if ("grpc" in $$parsedSource) {
            $$parsedSource["grpc"] = $$createField30_0($$parsedSource["grpc"]);
        }
        if ("h2" in $$parsedSource) {
            $$parsedSource["h2"] = $$createField31_0($$parsedSource["h2"]);
        }
        return new ProxySettings(/** @type {Partial<ProxySettings>} */($$parsedSource));
    }
}

/**
 * RealitySettings REALITY 配置。
 * 分享链接中对应 pbk/sid/spx/fp 参数；Xray 要求 security=reality 时必须提供
 * realitySettings，缺失会直接拒绝加载整份配置。
 */
export class RealitySettings {
    /**
     * Creates a new RealitySettings instance.
     * @param {Partial<RealitySettings>} [$$source = {}] - The source object to create the RealitySettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 服务端公钥 (pbk)
             * @member
             * @type {string | undefined}
             */
            this["publicKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 短 ID (sid)
             * @member
             * @type {string | undefined}
             */
            this["shortId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 爬虫路径 (spx)
             * @member
             * @type {string | undefined}
             */
            this["spiderX"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * uTLS 指纹 (fp)
             * @member
             * @type {string | undefined}
             */
            this["fingerprint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SNI，通常取自 sni 参数
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RealitySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RealitySettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RealitySettings(/** @type {Partial<RealitySettings>} */($$parsedSource));
    }
}

/**
 * SessionRelay 动态会话代理：单端口按客户端用户名动态切换住宅代理出口 IP。
 * 
 * 住宅代理服务商把会话标识编码在用户名里（如 login__cr.au;sessid.123），
 * 传统做法要为每个会话开一个端口。此类型只占一个端口，客户端换用户名
 * 即换出口 IP，无需重启进程。上游连接可经前置节点加速。
 * 监听端口为混合端口，HTTP 与 SOCKS5 客户端都可接入。
 */
export class SessionRelay {
    /**
     * Creates a new SessionRelay instance.
     * @param {Partial<SessionRelay>} [$$source = {}] - The source object to create the SessionRelay.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * 别名
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * 本地监听端口（混合端口，同时支持 HTTP/SOCKS5 客户端）
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("upstreamAddr" in $$source)) {
            /**
             * 上游住宅网关，如 gw.dataimpulse.com:823
             * @member
             * @type {string}
             */
            this["upstreamAddr"] = "";
        }
        if (!("usernameTemplate" in $$source)) {
            /**
             * 上游用户名模板，含 {session} 占位符；为空表示透传客户端用户名
             * @member
             * @type {string}
             */
            this["usernameTemplate"] = "";
        }
        if (!("upstreamPassword" in $$source)) {
            /**
             * 上游固定密码
             * @member
             * @type {string}
             */
            this["upstreamPassword"] = "";
        }
        if (!("localPassword" in $$source)) {
            /**
             * 客户端需提供的密码（为空则不校验）
             * @member
             * @type {string}
             */
            this["localPassword"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 前置加速节点 ID（普通节点/链式/故障转移）。
             * 空表示直连上游；FollowGlobalPreProxy 表示跟随全局前置代理设置。
             * @member
             * @type {string | undefined}
             */
            this["preProxyNodeId"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * 启动状态
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("lastError" in $$source)) {
            /**
             * 最近一次启动失败原因（成功后清空）
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 所属分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("groupName" in $$source)) {
            /**
             * 所属分组名称
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (!("activeConns" in $$source)) {
            /**
             * 运行时统计（不持久化速度，仅回显）
             * 当前活跃连接数
             * @member
             * @type {number}
             */
            this["activeConns"] = 0;
        }
        if (!("totalConns" in $$source)) {
            /**
             * 累计连接数
             * @member
             * @type {number}
             */
            this["totalConns"] = 0;
        }
        if (!("sessionCount" in $$source)) {
            /**
             * 出现过的不同会话数
             * @member
             * @type {number}
             */
            this["sessionCount"] = 0;
        }
        if (!("traffic" in $$source)) {
            /**
             * 流量统计
             * @member
             * @type {TrafficStats}
             */
            this["traffic"] = (new TrafficStats());
        }
        if (!("lastStartTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastStartTime"] = "";
        }
        if (!("lastStopTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastStopTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRelay instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionRelay}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("traffic" in $$parsedSource) {
            $$parsedSource["traffic"] = $$createField15_0($$parsedSource["traffic"]);
        }
        return new SessionRelay(/** @type {Partial<SessionRelay>} */($$parsedSource));
    }
}

/**
 * SpeedTestConfig 测速配置（下载测速的目标 URL 与请求头）
 */
export class SpeedTestConfig {
    /**
     * Creates a new SpeedTestConfig instance.
     * @param {Partial<SpeedTestConfig>} [$$source = {}] - The source object to create the SpeedTestConfig.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * 测速下载 URL（空则用默认）
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * 自定义请求头（空则用默认浏览器请求头）
             * @member
             * @type {{ [_: string]: string }}
             */
            this["headers"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeedTestConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpeedTestConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        return new SpeedTestConfig(/** @type {Partial<SpeedTestConfig>} */($$parsedSource));
    }
}

/**
 * Subscription 订阅配置
 */
export class Subscription {
    /**
     * Creates a new Subscription instance.
     * @param {Partial<Subscription>} [$$source = {}] - The source object to create the Subscription.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 订阅ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 订阅名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * 订阅链接
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 订阅类型: clash, v2ray, sip008, base64
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 关联的分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("autoUpdate" in $$source)) {
            /**
             * 是否自动更新
             * @member
             * @type {boolean}
             */
            this["autoUpdate"] = false;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * 更新间隔（小时）
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            /**
             * 最后更新时间
             * @member
             * @type {string}
             */
            this["lastUpdate"] = "";
        }
        if (!("nextUpdate" in $$source)) {
            /**
             * 下次更新时间
             * @member
             * @type {string}
             */
            this["nextUpdate"] = "";
        }
        if (!("nodeCount" in $$source)) {
            /**
             * 节点数量
             * @member
             * @type {number}
             */
            this["nodeCount"] = 0;
        }
        if (!("updateMode" in $$source)) {
            /**
             * 更新方式: direct（直连，默认）, system（系统代理）, proxy（指定节点/链式/故障转移）
             * @member
             * @type {string}
             */
            this["updateMode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * UpdateMode 为 proxy 时使用的节点/链式代理/故障转移 ID
             * @member
             * @type {string | undefined}
             */
            this["updateProxyId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Subscription}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subscription(/** @type {Partial<Subscription>} */($$parsedSource));
    }
}

/**
 * TLSSettings TLS配置
 */
export class TLSSettings {
    /**
     * Creates a new TLSSettings instance.
     * @param {Partial<TLSSettings>} [$$source = {}] - The source object to create the TLSSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 服务器名称 (SNI)
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ALPN协议列表
             * @member
             * @type {string[] | undefined}
             */
            this["alpn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 允许不安全连接
             * @member
             * @type {boolean | undefined}
             */
            this["allowInsecure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * uTLS 指纹 (fp)，如 chrome/firefox
             * @member
             * @type {string | undefined}
             */
            this["fingerprint"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TLSSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TLSSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("alpn" in $$parsedSource) {
            $$parsedSource["alpn"] = $$createField1_0($$parsedSource["alpn"]);
        }
        return new TLSSettings(/** @type {Partial<TLSSettings>} */($$parsedSource));
    }
}

/**
 * TrafficStats 节点流量统计（字节）
 */
export class TrafficStats {
    /**
     * Creates a new TrafficStats instance.
     * @param {Partial<TrafficStats>} [$$source = {}] - The source object to create the TrafficStats.
     */
    constructor($$source = {}) {
        if (!("todayUp" in $$source)) {
            /**
             * 今日上传
             * @member
             * @type {number}
             */
            this["todayUp"] = 0;
        }
        if (!("todayDown" in $$source)) {
            /**
             * 今日下载
             * @member
             * @type {number}
             */
            this["todayDown"] = 0;
        }
        if (!("totalUp" in $$source)) {
            /**
             * 累计上传
             * @member
             * @type {number}
             */
            this["totalUp"] = 0;
        }
        if (!("totalDown" in $$source)) {
            /**
             * 累计下载
             * @member
             * @type {number}
             */
            this["totalDown"] = 0;
        }
        if (!("todayDate" in $$source)) {
            /**
             * 今日统计对应的日期（yyyy-mm-dd），跨天自动清零
             * @member
             * @type {string}
             */
            this["todayDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrafficStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrafficStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrafficStats(/** @type {Partial<TrafficStats>} */($$parsedSource));
    }
}

/**
 * UpdateConfig 应用更新设置
 */
export class UpdateConfig {
    /**
     * Creates a new UpdateConfig instance.
     * @param {Partial<UpdateConfig>} [$$source = {}] - The source object to create the UpdateConfig.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * 是否已由用户/程序写过（区分零值与显式关闭）
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("autoCheck" in $$source)) {
            /**
             * 启动时自动检查更新
             * @member
             * @type {boolean}
             */
            this["autoCheck"] = false;
        }
        if (!("autoDownload" in $$source)) {
            /**
             * 发现新版本时自动下载并安装
             * @member
             * @type {boolean}
             */
            this["autoDownload"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateConfig(/** @type {Partial<UpdateConfig>} */($$parsedSource));
    }
}

/**
 * UpdateInfo 更新检查结果（API 回显）
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("releaseName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseName"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseNotes"] = "";
        }
        if (!("releaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseURL"] = "";
        }
        if (!("assetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetName"] = "";
        }
        if (!("assetURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetURL"] = "";
        }
        if (!("assetSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assetSize"] = 0;
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * WSSettings WebSocket配置
 */
export class WSSettings {
    /**
     * Creates a new WSSettings instance.
     * @param {Partial<WSSettings>} [$$source = {}] - The source object to create the WSSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * WebSocket路径
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP头
             * @member
             * @type {{ [_: string]: string } | undefined}
             */
            this["headers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WSSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WSSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        return new WSSettings(/** @type {Partial<WSSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TrafficStats.createFrom;
const $$createType2 = ProxySettings.createFrom;
const $$createType3 = TLSSettings.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = RealitySettings.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = WSSettings.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = GRPCSettings.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = H2Settings.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
