// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GRPCSettings gRPC配置
 */
export class GRPCSettings {
    /**
     * Creates a new GRPCSettings instance.
     * @param {Partial<GRPCSettings>} [$$source = {}] - The source object to create the GRPCSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * gRPC服务名
             * @member
             * @type {string | undefined}
             */
            this["serviceName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GRPCSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GRPCSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GRPCSettings(/** @type {Partial<GRPCSettings>} */($$parsedSource));
    }
}

/**
 * Group 节点分组
 */
export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 分组ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 分组名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 分组描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 来源: manual, subscription
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 关联的订阅ID（如果来自订阅）
             * @member
             * @type {string | undefined}
             */
            this["subscriptionId"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

/**
 * H2Settings HTTP/2配置
 */
export class H2Settings {
    /**
     * Creates a new H2Settings instance.
     * @param {Partial<H2Settings>} [$$source = {}] - The source object to create the H2Settings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * HTTP/2路径
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP/2 Host
             * @member
             * @type {string[] | undefined}
             */
            this["host"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new H2Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {H2Settings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("host" in $$parsedSource) {
            $$parsedSource["host"] = $$createField1_0($$parsedSource["host"]);
        }
        return new H2Settings(/** @type {Partial<H2Settings>} */($$parsedSource));
    }
}

/**
 * ProxyRule 代理规则结构
 */
export class ProxyRule {
    /**
     * Creates a new ProxyRule instance.
     * @param {Partial<ProxyRule>} [$$source = {}] - The source object to create the ProxyRule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * 别名
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("localType" in $$source)) {
            /**
             * 本地代理类型: socks 或 http
             * @member
             * @type {string}
             */
            this["localType"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * 本地代理端口
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("protocol" in $$source)) {
            /**
             * 远程协议类型: shadowsocks, vmess, vless, trojan
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("serverAddr" in $$source)) {
            /**
             * 服务器地址
             * @member
             * @type {string}
             */
            this["serverAddr"] = "";
        }
        if (!("serverPort" in $$source)) {
            /**
             * 服务器端口
             * @member
             * @type {number}
             */
            this["serverPort"] = 0;
        }
        if (!("settings" in $$source)) {
            /**
             * 协议相关配置
             * @member
             * @type {ProxySettings}
             */
            this["settings"] = (new ProxySettings());
        }
        if (!("realIp" in $$source)) {
            /**
             * 真实IP
             * @member
             * @type {string}
             */
            this["realIp"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * 启动状态
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("processId" in $$source)) {
            /**
             * 进程ID
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("latency" in $$source)) {
            /**
             * 测速相关字段
             * TCP 延迟（毫秒）
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            /**
             * 下载速度（MB/s）
             * @member
             * @type {number}
             */
            this["downloadSpeed"] = 0;
        }
        if (!("lastTestTime" in $$source)) {
            /**
             * 最后测速时间
             * @member
             * @type {string}
             */
            this["lastTestTime"] = "";
        }
        if (!("testStatus" in $$source)) {
            /**
             * 测速状态: idle, testing, success, failed
             * @member
             * @type {string}
             */
            this["testStatus"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 分组相关字段
             * 所属分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("groupName" in $$source)) {
            /**
             * 所属分组名称
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 订阅链接（如果来自订阅）
             * @member
             * @type {string | undefined}
             */
            this["subscriptionUrl"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * 来源: manual（手动添加）, subscription（订阅导入）
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyRule}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField7_0($$parsedSource["settings"]);
        }
        return new ProxyRule(/** @type {Partial<ProxyRule>} */($$parsedSource));
    }
}

/**
 * ProxySettings 代理协议设置（根据协议类型使用不同字段）
 */
export class ProxySettings {
    /**
     * Creates a new ProxySettings instance.
     * @param {Partial<ProxySettings>} [$$source = {}] - The source object to create the ProxySettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Shadowsocks 配置
             * 加密方法
             * @member
             * @type {string | undefined}
             */
            this["ssMethod"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 密码
             * @member
             * @type {string | undefined}
             */
            this["ssPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VMess 配置
             * 用户ID (UUID)
             * @member
             * @type {string | undefined}
             */
            this["vmessUserId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 额外ID
             * @member
             * @type {number | undefined}
             */
            this["vmessAlterId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密方式 (auto, aes-128-gcm, chacha20-poly1305, none)
             * @member
             * @type {string | undefined}
             */
            this["vmessSecurity"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VLESS 配置
             * 用户ID (UUID)
             * @member
             * @type {string | undefined}
             */
            this["vlessUserId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 流控模式 (xtls-rprx-vision等)
             * @member
             * @type {string | undefined}
             */
            this["vlessFlow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 加密方式（通常为 none）
             * @member
             * @type {string | undefined}
             */
            this["vlessEncryption"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Trojan 配置
             * Trojan密码
             * @member
             * @type {string | undefined}
             */
            this["trojanPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP 代理配置
             * HTTP 代理用户名（可选）
             * @member
             * @type {string | undefined}
             */
            this["httpUsername"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP 代理密码（可选）
             * @member
             * @type {string | undefined}
             */
            this["httpPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SOCKS 代理配置
             * SOCKS 代理用户名（可选）
             * @member
             * @type {string | undefined}
             */
            this["socksUsername"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SOCKS 代理密码（可选）
             * @member
             * @type {string | undefined}
             */
            this["socksPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SOCKS 版本 (socks4, socks5, 默认 socks5)
             * @member
             * @type {string | undefined}
             */
            this["socksVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 通用传输层配置
             * 传输协议: tcp, ws, grpc, h2
             * @member
             * @type {string | undefined}
             */
            this["network"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 传输层安全: none, tls
             * @member
             * @type {string | undefined}
             */
            this["security"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TLS配置
             * @member
             * @type {TLSSettings | null | undefined}
             */
            this["tls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * WebSocket配置
             * @member
             * @type {WSSettings | null | undefined}
             */
            this["ws"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * gRPC配置
             * @member
             * @type {GRPCSettings | null | undefined}
             */
            this["grpc"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP/2配置
             * @member
             * @type {H2Settings | null | undefined}
             */
            this["h2"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxySettings}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType3;
        const $$createField17_0 = $$createType5;
        const $$createField18_0 = $$createType7;
        const $$createField19_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tls" in $$parsedSource) {
            $$parsedSource["tls"] = $$createField16_0($$parsedSource["tls"]);
        }
        if ("ws" in $$parsedSource) {
            $$parsedSource["ws"] = $$createField17_0($$parsedSource["ws"]);
        }
        if ("grpc" in $$parsedSource) {
            $$parsedSource["grpc"] = $$createField18_0($$parsedSource["grpc"]);
        }
        if ("h2" in $$parsedSource) {
            $$parsedSource["h2"] = $$createField19_0($$parsedSource["h2"]);
        }
        return new ProxySettings(/** @type {Partial<ProxySettings>} */($$parsedSource));
    }
}

/**
 * Subscription 订阅配置
 */
export class Subscription {
    /**
     * Creates a new Subscription instance.
     * @param {Partial<Subscription>} [$$source = {}] - The source object to create the Subscription.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 订阅ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 订阅名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * 订阅链接
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 订阅类型: clash, v2ray, sip008, base64
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * 关联的分组ID
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("autoUpdate" in $$source)) {
            /**
             * 是否自动更新
             * @member
             * @type {boolean}
             */
            this["autoUpdate"] = false;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * 更新间隔（小时）
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            /**
             * 最后更新时间
             * @member
             * @type {string}
             */
            this["lastUpdate"] = "";
        }
        if (!("nextUpdate" in $$source)) {
            /**
             * 下次更新时间
             * @member
             * @type {string}
             */
            this["nextUpdate"] = "";
        }
        if (!("nodeCount" in $$source)) {
            /**
             * 节点数量
             * @member
             * @type {number}
             */
            this["nodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Subscription}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subscription(/** @type {Partial<Subscription>} */($$parsedSource));
    }
}

/**
 * TLSSettings TLS配置
 */
export class TLSSettings {
    /**
     * Creates a new TLSSettings instance.
     * @param {Partial<TLSSettings>} [$$source = {}] - The source object to create the TLSSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 服务器名称 (SNI)
             * @member
             * @type {string | undefined}
             */
            this["serverName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ALPN协议列表
             * @member
             * @type {string[] | undefined}
             */
            this["alpn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 允许不安全连接
             * @member
             * @type {boolean | undefined}
             */
            this["allowInsecure"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TLSSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TLSSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("alpn" in $$parsedSource) {
            $$parsedSource["alpn"] = $$createField1_0($$parsedSource["alpn"]);
        }
        return new TLSSettings(/** @type {Partial<TLSSettings>} */($$parsedSource));
    }
}

/**
 * WSSettings WebSocket配置
 */
export class WSSettings {
    /**
     * Creates a new WSSettings instance.
     * @param {Partial<WSSettings>} [$$source = {}] - The source object to create the WSSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * WebSocket路径
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTP头
             * @member
             * @type {{ [_: string]: string } | undefined}
             */
            this["headers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WSSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WSSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        return new WSSettings(/** @type {Partial<WSSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProxySettings.createFrom;
const $$createType2 = TLSSettings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = WSSettings.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = GRPCSettings.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = H2Settings.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
